app/floods/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class SurgingSeasForm(FlaskForm):
    city_name = StringField('<h6 style="color:#4976d0">Name of the city</h6>', validators=[DataRequired()])
    how_many_metters = StringField('<h6 class="text-danger">Increase of seas level [m]</h6>', validators=[DataRequired()])
    submit = SubmitField('Load link')

app/weather/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class WeatherForm(FlaskForm):
    city_name = StringField('', validators=[DataRequired()])
    submit = SubmitField('Add city')

app/floods/routes.py
from flask import render_template, url_for, flash, redirect, request
from app import db
from app.floods.forms import SurgingSeasForm
from app.models import SurgingSeasCard
from flask_login import current_user
import requests
from app.utilities import check_for_duplicates, check_for_the_same_parameters, is_int
from flask import Blueprint

floods_bp = Blueprint('floods_bp', __name__)


@floods_bp.route('/floods', methods=['POST', 'GET'])
def floods():
    form = SurgingSeasForm()

    if form.validate_on_submit():
        try:
            url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid=88e12df4038659e5d9e36114cd2599d6'
            r = requests.get(url.format(form.city_name.data)).json()
            coordinates = [r['coord']['lon'], r['coord']['lat']]
            link_for_city = f'https://www.floodmap.net/?ll={coordinates[1]},{coordinates[0]}&z=11&e={form.how_many_metters.data}'
            new_city = SurgingSeasCard(city=form.city_name.data, link=link_for_city, lvl_increase=form.how_many_metters.data, user_id=current_user.id)
            if check_for_the_same_parameters(new_city, SurgingSeasCard) == True:
                flash('You already have a link with those parameters.', 'danger')
            elif is_int(form.how_many_metters.data) == False:
                flash('"Increase of seas level" must be an integer.', 'danger')
            else:
                db.session.add(new_city)
                db.session.commit()
                db.session.close()
                flash(f'Link for {form.city_name.data} added successfully.', 'success')
        except KeyError:
            flash(f'There is not such a city "{form.city_name.data}". Try again with another one.', 'danger')
        return redirect(url_for('floods_bp.floods'))

    if current_user.is_authenticated:
        data = SurgingSeasCard.query.filter(SurgingSeasCard.user_id == current_user.id)
        return render_template('floods.html', form=form, data=data)
    else:
        return render_template('not_signed_in.html')


@floods_bp.route('/delete_link/<int:link>')
def delete_link(link):
    link_to_delete = SurgingSeasCard.query.filter_by(id=link).first()
    local_object = db.session.merge(link_to_delete)

    db.session.delete(local_object)
    db.session.commit()
    db.session.close()
    flash(f'Link for "{link_to_delete.city}" deleted successfully.', 'success')

    return redirect(url_for('floods_bp.floods'))

app/main/routes.py
from flask import Blueprint, render_template

about_bp = Blueprint('about_bp', __name__)


@about_bp.route('/')
@about_bp.route('/about')
def about():
    return render_template('about.html')

app/users/routes.py
from flask import render_template, url_for, flash, redirect, Flask, request
from app import db, bcrypt
from app.users.forms import RegistrationForm, LoginForm
from app.models import User, WeatherCard, SurgingSeasCard
from flask_login import login_user, logout_user, current_user
import requests
from flask import Blueprint

users_bp = Blueprint('users_bp', __name__)


@users_bp.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('weather_bp.weather'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash(f'You have been logged in successfully.', 'success')
            return redirect(url_for('weather_bp.weather'))
        else:
            flash(f'Login unsuccessfull. Please, check your username and password.', 'danger')
    return render_template('login.html', titile='Login', form=form)


@users_bp.route('/logout')
def logout():
    user = User.query.filter_by(username=current_user.username).first()
    logout_user()
    flash(f'Logout for {user.username} succesfull.', 'success')
    return redirect(url_for('about_bp.about'))


@users_bp.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('weather_bp.weather'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        db.session.close()
        flash(f'Account has been created for {form.username.data}. You are now able to log in.', 'success')
        return redirect(url_for('users_bp.login'))
    return render_template('register.html', titile='Register', form=form)


@users_bp.route('/delete_account/<int:user>')
def delete_account(user):
    links_to_delete = SurgingSeasCard.query.filter_by(user_id=user)
    for link in links_to_delete:
        local_object = db.session.merge(link)
        db.session.delete(local_object)
        db.session.commit()
        db.session.close()

    cards_to_delete = WeatherCard.query.filter_by(user_id=user)
    for card in cards_to_delete:
        local_object = db.session.merge(card)
        db.session.delete(local_object)
        db.session.commit()
        db.session.close()

    acc_to_delete = User.query.filter_by(id=user).first()
    local_object = db.session.merge(acc_to_delete)
    db.session.delete(local_object)
    db.session.commit()
    db.session.close()
    logout_user()   #for some reason next registered user is automaticly authenticated without logout

    flash(f'Account for "{acc_to_delete.username}" deleted successfully.', 'success')

    return redirect(url_for('about_bp.about'))

app/weather/routes.py
from flask import render_template, url_for, flash, redirect, Flask, request
from app import bcrypt, db
from app.weather.forms import WeatherForm
from app.models import WeatherCard
from flask_login import current_user
import requests
from app.utilities import check_for_duplicates
from flask import Blueprint

weather_bp = Blueprint('weather_bp', __name__)


@weather_bp.route('/weather', methods=['POST', 'GET'])
def weather():
    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid=88e12df4038659e5d9e36114cd2599d6'
    form = WeatherForm()

    if form.validate_on_submit():
        new_city = WeatherCard(city=form.city_name.data, user_id=current_user.id)
        if check_for_duplicates(new_city, WeatherCard) == True:
            flash(f'You already have a card for {form.city_name.data}.', 'danger')
        else:
            try:
                r = requests.get(url.format(new_city.city)).json()
                weather = r['weather'][0]['description']
                db.session.add(new_city)
                db.session.commit()
                db.session.close()
                flash(f'Card for "{form.city_name.data}" added successfully.', 'success')
            except KeyError:
                flash(f'There is not such a city "{form.city_name.data}". Try again with another one.', 'danger')
        return redirect(url_for('weather_bp.weather'))

    WeatherCards = WeatherCard.query.all()
    weather_data = []

    for card in WeatherCards:
        r = requests.get(url.format(card.city)).json()

        '''I am checking database once again, because sometimes records go in when they shouldn't.'''
        try:
            weather = {
                'city': card.city,
                'temperature': round((r['main']['temp']-32)*0.5556, 2),
                'description': r['weather'][0]['description'],
                'icon': r['weather'][0]['icon'],
                'pressure': r['main']['pressure'],
                'wind': r['wind']['speed'],
                'user': card.user_id,
                'id': card.id,
            }
            weather_data.append(weather)
        except KeyError:
            local_object = db.session.merge(card)
            db.session.delete(local_object)
            db.session.commit()
            db.session.close()

    if current_user.is_authenticated:
        return render_template('weather.html', form=form, weather_data=weather_data)
    else:
        return render_template('not_signed_in.html')


@weather_bp.route('/delete_card/<int:card>')
def delete_card(card):
    card_to_delete = WeatherCard.query.filter_by(id=card).first()
    local_object = db.session.merge(card_to_delete)

    db.session.delete(local_object)
    db.session.commit()
    db.session.close()
    flash(f'Card for "{card_to_delete.city}" deleted successfully.', 'success')

    return redirect(url_for('weather_bp.weather'))

app/templates/about.html
{% extends "layout.html" %}

{% block menubar %}
<a class="col-lg-1 font-weight-bolder text-warning" style="text-decoration: none" href="{{ url_for('about_bp.about') }}">About</a>
<a class="col-lg-1 font-weight-bolder text-light" style="text-decoration: none" href="{{ url_for('weather_bp.weather') }}">Weather</a>
<a class="col-lg-3 font-weight-bolder text-light" style="text-decoration: none" href="{{ url_for('floods_bp.floods') }}">Surging Seas</a>
{% endblock menubar %}

{% block content %}
<info_section class="row">
    <h4 class="highlight col-12 mt-3 text-light text-center rounded py-3" style="background-color:#33cccc">This website allows You:</h4>
    <h4 class="highlight_2 col-12 mt-3 text-light text-center rounded py-3" style="background-color:#33cccc">To check weather in multiple cities. All of them will be remembered.</h4>
    <h4 class="highlight_3 col-12 mt-3 text-light text-center rounded py-3" style="background-color:#33cccc">To check if there is risk of flood in Your zone.</h4>
</info_section>
{% endblock content %}

app/templates/floods.html
{% extends "layout.html" %}

{% block menubar %}
<a class="col-lg-1 font-weight-bolder text-light" style="text-decoration: none" href="{{ url_for('about_bp.about') }}">About</a>
<a class="col-lg-1 font-weight-bolder text-light" style="text-decoration: none" href="{{ url_for('weather_bp.weather') }}">Weather</a>
<a class="col-lg-3 font-weight-bolder text-warning" style="text-decoration: none" href="{{ url_for('floods_bp.floods') }}">Surging Seas</a>
{% endblock menubar %}

{% block content %}

<div class="row mt-3">
    <h5 class="highlight_4 offset-lg-4 col-lg-4 font-weight-bolder text-center text-info">Which sea level will we lock in?</h5>
    <form class="offset-lg-4 col-lg-4 card card-body bg-light" method="POST" action="">
        <data class="row">
            {{ form.hidden_tag() }}
            <city class="col-lg-12">
                {{ form.city_name.label(class="form-control-label") }}
                {{ form.city_name(class="form-control form-control-md") }}
            </city>
            <temperature class="col-lg-12">
                {{ form.how_many_metters.label(class="form-control-label") }}
                {{ form.how_many_metters(class="form-control form-control-md") }}
            </temperature>
            <p class="col-lg-12 text-center">
                <br>
                {{ form.submit(class="btn btn-outline-info") }}
            </p>
            <h8 class="highlight_5 col-lg-12 text-info">
                Note: Data says, that by 2100 we will reach increase of 0.69[m].
            </h8>
        </data>
    </form>
    {% for card in data %}
    <city class="offset-lg-4 col-lg-4 card card-body bg-light mt-3">
        <link_section class="row">
            <h5 class="col-8 text-left"><a style="color:#4976d0" href="{{ card.link }}" target="_blank">{{ card.city }}</a>, <span class="text-danger">{{ card.lvl_increase }}m</span></h5>
            <button class="col-4 text-right close" aria-label="Close">
                <a href="{{ url_for('floods_bp.delete_link', link=card.id) }}">
                    <span aria-hidden="true">&times;</span>
                </a>
            </button>
        </link_section>
    </city>
    {% endfor %}
</div>

{% endblock content %}
https://www.floodmap.net/?ll=16.272864,18.682001&z=10&e=10

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>weather app</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="app/templates/static.css" type="text/css">
    <script src="https://unpkg.com/scrollreveal"></script>
</head>

<body>
    <div class="container">
        <header class="row rounded bg-info p-3">

            <!------------------------------------------------------------------------------------------------------------->
            {% block menubar %}
            {% endblock menubar %}
            <!------------------------------------------------------------------------------------------------------------->

            {% if current_user.is_authenticated %}
            <right_nav class="offset-lg-3 col-lg-4 text-right">
                <a href="#collapseTarget" data-toggle="collapse" class="text-light font-weight-bolder" style="text-decoration: none">{{ current_user.username }}</a>
                    <user_section>
                        <div class="row">
                            <a id="collapseTarget" class="col-12 collapse text-light" style="text-decoration: none" href="{{ url_for('users_bp.delete_account', user=current_user.id) }}">Delete Account</a>
                        </div>
                        <div class="row">
                            <a id="collapseTarget" class="col-12 collapse text-light" style="text-decoration: none" href="{{ url_for('users_bp.logout') }}">Logout</a>
                        </div>
                    </user_section>
            </right_nav>
            {% else %}
                <a class="offset-lg-5 col-lg-1 text-light" style="text-decoration: none" href="{{ url_for('users_bp.login') }}">Login</a>
                <a class="col-lg-1 text-light" style="text-decoration: none" href="{{ url_for('users_bp.register') }}">Register</a>
            {% endif %}
        </header>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="row">
                        <div class="col-md-12 alert alert-{{ category }} p-1">
                            {{ message }}
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <!------------------------------------------------------------------------------------------------------------->
        {% block content %}
        {% endblock %}
        <!------------------------------------------------------------------------------------------------------------->

    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <script>
        window.sr=ScrollReveal();

        sr.reveal('.highlight', {
        duration: 2000,
        origin:'left',
        distance:'100px'
        })

        sr.reveal('.highlight_2', {
        duration: 2000,
        origin:'left',
        distance:'100px',
        delay:'400'
        })

        sr.reveal('.highlight_3', {
        duration: 2000,
        origin:'left',
        distance:'100px',
        delay:'800'
        })

        sr.reveal('.highlight_4', {
        duration: 1000,
        origin:'top',
        distance:'100px'
        })

        sr.reveal('.highlight_5', {
        duration: 1000,
        origin:'bottom',
        distance:'100px',
        delay:'800'
        })


    </script>

</body>
</html>

app/templates/login.html
{% extends "layout.html" %}

{% block menubar %}
<a class="col-lg-1 font-weight-bolder text-light" style="text-decoration: none" href="{{ url_for('about_bp.about') }}">About</a>
<a class="col-lg-1 font-weight-bolder text-light" style="text-decoration: none" href="{{ url_for('weather_bp.weather') }}">Weather</a>
<a class="col-lg-3 font-weight-bolder text-light" style="text-decoration: none" href="{{ url_for('floods_bp.floods') }}">Surging Seas</a>
{% endblock menubar %}

{% block content %}

<div class="row">
    <form class="col-md-12 mt-3 p-3 bg-light" method="POST" action="">
        {{ form.hidden_tag() }}
        <div>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div>
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div>
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check mb-3">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </div>
        <div>
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    <div class="m-3">
        <small class="text-muted">
            Don't have an account? <a class="ml-2" href="{{ url_for('users_bp.register') }}">Sign up</a>
        </small>
    </div>
</div>
{% endblock content %}

app/templates/not_signed_in.html
{% extends "layout.html" %}

{% block menubar %}
<a class="col-lg-1 font-weight-bolder text-light" style="text-decoration: none" href="{{ url_for('about_bp.about') }}">About</a>
<a class="col-lg-1 font-weight-bolder text-light" style="text-decoration: none" href="{{ url_for('weather_bp.weather') }}">Weather</a>
<a class="col-lg-3 font-weight-bolder text-light" style="text-decoration: none" href="{{ url_for('floods_bp.floods') }}">Surging Seas</a>
{% endblock menubar %}

{% block content %}

<div class="row mt-3">
    <div class="col-md-12 alert alert-primary">
        To see this content, you need to log in first.
    </div>
</div>

{% endblock content %}

app/templates/register.html
{% extends "layout.html" %}

{% block menubar %}
<a class="col-lg-1 font-weight-bolder text-light" style="text-decoration: none" href="{{ url_for('about_bp.about') }}">About</a>
<a class="col-lg-1 font-weight-bolder text-light" style="text-decoration: none" href="{{ url_for('weather_bp.weather') }}">Weather</a>
<a class="col-lg-3 font-weight-bolder text-light" style="text-decoration: none" href="{{ url_for('floods_bp.floods') }}">Surging Seas</a>
{% endblock menubar %}

{% block content %}

<div class="row">
    <form class="col-lg-12 mt-3 p-3 bg-light" method="POST" action="">
        {{ form.hidden_tag() }}
        <div>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div>
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div>
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div>
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </div>
        <div class="mt-4">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    <div class="m-3">
        <small class="text-muted">
            Already have an account? <a class="ml-2" href="{{ url_for('users_bp.login') }}">Sign in</a>
        </small>
    </div>
</div>

{% endblock content %}

app/templates/weather.html
{% extends "layout.html" %}

{% block menubar %}
<a class="col-lg-1 font-weight-bolder text-light" style="text-decoration: none" href="{{ url_for('about_bp.about') }}">About</a>
<a class="col-lg-1 font-weight-bolder text-warning" style="text-decoration: none" href="{{ url_for('weather_bp.weather') }}">Weather</a>
<a class="col-lg-3 font-weight-bolder text-light" style="text-decoration: none" href="{{ url_for('floods_bp.floods') }}">Surging Seas</a>
{% endblock menubar %}

{% block content %}

<div class="mt-3">
    <div class="row">
        {% for city in weather_data %}
        {% if current_user.id == city.user %}
        <weather_section class="col-md-4 card card-body bg-light">
            <weather class="row">
                <icon_section class="col-md-1 img is-50x50">
                    <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
                </icon_section>
                <info_section class="offset-md-1 col-md-8">
                    <h3 class="card-title" style="color:#4976d0">{{ city["city"] }}</h3>
                    <data style="color:#ff9999">
                        <h6>{{ city["temperature"] }}°C</h6>
                        <h6>{{ city["description"] }}</h6>
                        <h6><span style="color:#7194da">Wind speed: </span>{{ city["wind"] }} km/h</h6>
                        <h6><span style="color:#7194da">Pressure: </span>{{ city["pressure"] }} h/Pa</h6>
                    </data>
                </info_section>
                <button_section class="col-md-2">
                    <button type="button" class="close" aria-label="Close">
                        <a href="{{ url_for('weather_bp.delete_card', card=city.id) }}">
                            <span aria-hidden="true">&times;</span>
                        </a>
                    </button>
                </button_section>
            </weather>
        </weather_section>
        {% endif %}
        {% endfor %}

        <input_section class="col-md-4 card card-body">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <section class="row my-4">
                    <p class="col-md-8">
                        {{ form.city_name.label(class="form-control-label") }}
                        {{ form.city_name(class="form-control form-control-md") }}
                    </p>
                    <p class="col-md-4">
                        <br>
                        {{ form.submit(class="btn btn-outline-info") }}
                    </p>
                </section>
            </form>
        </input_section>
    </div>
</div>

{% endblock content %}